server_ip: '192.168.0.103'
server_port: 8000
collectors:
  'dssg_monitor.collectors.temperature.BME280TemperatureCollector':
  'dssg_monitor.collectors.temperature.DS18B20TemperatureCollector':
    names: ["aircon"]
